### PR TITLE
merge/engine: merge engine into main repository

### PR DESCRIPTION
**Pull request by RLKRo**
merge/engine: add mypy check to lint

merge/engine: Fix typos

merge/engine: Initialize merged repository

- Move df_engine to dff/core as engine
- Rebuild docs
- Rename Engine to Framework
- Remove requirements txts

### CODE REVIEW

**Comment by pseusys** [comment]
1. Shouldn't we exclude `apiref` from VCS?
2. Tests are failing...

**Comment by RLKRo** [comment]
> 2. Tests are failing...

Some of them are failing.

Codestyle is failing because I added a mypy check -- something that wasn't present in the original **df_engine** repo.

Test coverage is failing for python versions below 3.9 which is why I propose we drop some of them:

- Python 3.6 EOL'd 9 months ago, should probably drop its' support
- Python 3.7 will EOL in 8 months. I think we should drop that too
- Python 3.8 will EOL in 3 years.

Currently there is a [patch](https://github.com/deeppavlov/dialog_flow_framework/blob/dev/utils/downgrade_patch.py) in utils that enables support for older python versions. I don't think this is a good practice so I suggest 2 solutions:

1. Support only Python 3.9+, remove the patch file.
2. Support Python 3.8+ but apply patches for Python3.8 directly to the source code and remove the patch file.

**Comment by pseusys** [comment]
Google Colab by default uses Python 3.7.
I don't think we should remove it's support - at least not until default Python version ib Colab is changed.
Do you require any help fixing Python version and/or code style (mypy) issues?

**Comment by RLKRo** [comment]
Good point.
But they say that they are working on a 3.8 update:

1. https://github.com/googlecolab/colabtools/issues/3057#issuecomment-1248635339
2. https://github.com/googlecolab/colabtools/issues/3057#issuecomment-1244713116

IMO if someone wants to use the framework with the 3.7 they can use the old packages from pip (df_engine instead of dff) that support 3.7. Assuming that colab updates to 3.8 in less than 8 months (EOL date of 3.7) this approach would work fine.

Fixing Python version is easy. But I think that mypy errors should be fixed by the people more familiar with the engine than me.

**Pull request merged**
