### PR TITLE
Add streamlit chat interface tutorial

### PR DESCRIPTION
**Pull request by RLKRo**
# Description

This PR adds a streamlit chat interface tutorial.
image

I added patches that clear the text input field when a text is sent and also added a patch that lets users send messages by pressing `Enter` instead of pressing `Send`.

This PR is awaiting following PRs to be merged:

- [x] #112 (this PR is based on it because they both use API endpoint and to preserve the order of tutorials)
- [x] https://github.com/AI-Yash/st-chat/pull/36 to allow installation of the `streamlit-chat` package on python 3.7. I tested that this tutorial works on python 3.7 so the only problem here is the setup requirement of that package.

This PR fails `tests/tutorials/test_format` tests because `tutorials/messengers/web_api_interface/4_streamlit_chat.py` uses `#` instead of `"""` for markdown cells. This is done because Streamlit treats `"""` strings as markdown statements and displays them on its page. Changing them to `#` solves this.

The doc building job succeeds while the format test fails so we should do something about it. **I propose removing `test_format` tests**: I don't think they are necessary.

### CODE REVIEW

**Comment by RLKRo** [comment]
As I mentioned in the body of this pull request, this markdown is treated by Streamlit as markdown cells that it has to display:
image

**Comment by pseusys** [comment]
> As I mentioned in the body of this pull request, markdown cells in this format are treated by Streamlit as markdown cells that it has to display: image

Can we test it too?

**Comment by pseusys** [comment]
In order to fix dependencies issue, can we switch to `streamlit-chat~=0.0.1`? Are there any breaking changes?

**Comment by RLKRo** [comment]
> Can we test it too?

Theoretically, yes.

But I don't know if we should (in that it is worth the time spent figuring out how to do that).

This tutorial is weakly dependent on `dff` (it only uses `Message` and includes an implementation without it). So changes to `dff` will likely not affect this tutorial.

I think if we are to test something out of the `web_api_interface` tutorials it should only be the `1_fastapi` one which would also cover this tutorial (because `4_streamlit_chat` uses the FastAPI endpoint to communicate with `pipeline` and the version of `streamlit` is frozen).

**Review by kudep — APPROVED** [review]

**Pull request merged**
