### PR TITLE
`:rtype:` removed for function aliases

### PR DESCRIPTION
**Pull request by pseusys**
1. Adding `:rtype:` to function alias documentation prevents Sphinx from generating return value description for them (ask @avsakharov about the designing base of this decision).
2. `ModuleName` is alias for `str`. It is intended to be an alias for string class, however Sphinx considers `str` to be a callable at the first place and generates a callable-like documentation entry for this alias. That's why this (and other for uniformity) type alias is wrapped with `NewType`.
3. Documentation strings for enum are brought out of the enum class docstring and distributed between enum members - for generated documentation beauty as well.

### CODE REVIEW

**Review by avsakharov — APPROVED** [review]

**Review by kudep — CHANGES_REQUESTED** [review]
- [x] tests

**Comment by pseusys** [comment]
> * [ ]  tests

As I have (eventually) pointed out before, tests are (sadly) not gonna pass before #46 is merged. Documentation generation issues are only fixed there.

**Review by kudep — APPROVED** [review]

**Review by RLKRo — CHANGES_REQUESTED** [review]
- [x] Please update the description of this PR to include the motivation behind those changes.
- [x] This PR introduces [new mypy errors](https://github.com/deeppavlov/dialog_flow_framework/files/10217996/mypy.diff.txt). This is mainly due to [the way type checkers process NewType](https://docs.python.org/3.10/library/typing.html#newtype).

**Comment by pseusys** [comment]
Motivation:
1. Adding `:rtype:` to function alias documentation prevents Sphinx from generating return value description for them (ask @avsakharov about the designing base of this decision).
2. `ModuleName` is alias for `str`. It is intended to be an alias for string class, however Sphinx considers `str` to be a callable at the first place and generates a callable-like documentation entry for this alias. That's why this (and other for uniformity) type alias is wrapped with `NewType`.
3. Documentation strings for enum are brought out of the enum class docstring and distributed between enum members - for generated documentation beauty as well.

**Comment by pseusys** [comment]
> Can this problem be solved by using [TypeAlias](https://docs.python.org/3/library/typing.html#typing.TypeAlias) instead?

It would be preferrable, but alas, `TypeAlias` was added in Python 10 only.

**Comment by RLKRo** [comment]
For older python versions it is available via `typing_extensions`.

**Review by RLKRo — APPROVED** [review]

**Pull request merged**
