### PR TITLE
Add patch for asyncio warning

### PR DESCRIPTION
**Pull request by ruthenian8**
# Description

Remove nest-asyncio warning that occurs during testing: test_full, Python 3.10, Ubuntu

# Checklist

- [x] I have covered the code with tests
- [x] I have added comments to my code to help others understand it
- [x] I have updated the documentation to reflect the changes
- [x] I have performed a self-review of the changes

### CODE REVIEW

**Review by kudep — CHANGES_REQUESTED** [review]
- [x] tests

**Review by kudep — CHANGES_REQUESTED** [review]
- [ ] and another warning 
image

**Review by RLKRo — COMMENTED** [review]
Could you also provide instructions on how to get these warnings?
On branch `dev` running `make test` only produces this:
```
tests/script/core/test_context.py::test_context 
-------------------------------- live log call ---------------------------------
"dff.script.core.context - WARNING - The `current_node` exists when an actor is running between `ActorStage.GET_PREVIOUS_NODE` and `ActorStage.FINISH_TURN`"
"dff.script.core.context - WARNING - The `overwrite_current_node_in_processing` function can only be run during processing functions."
PASSED                                                                   [ 76%]
```
Or are these warnings OS specific?

**Comment by ruthenian8** [comment]
> Could you also provide instructions on how to get these warnings? On branch `dev` running `make test` only produces this:
> 
> ```
> tests/script/core/test_context.py::test_context 
> -------------------------------- live log call ---------------------------------
> "dff.script.core.context - WARNING - The `current_node` exists when an actor is running between `ActorStage.GET_PREVIOUS_NODE` and `ActorStage.FINISH_TURN`"
> "dff.script.core.context - WARNING - The `overwrite_current_node_in_processing` function can only be run during processing functions."
> PASSED                                                                   [ 76%]
> ```
> 
> Or are these warnings OS specific?

On Ubuntu, Python3.10 used to throw:
(see test_full#554)

=============================== warnings summary ===============================
tests/context_storages/test_dbs.py::test_shelve
  /opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/nest_asyncio.py:45: DeprecationWarning: There is no current event loop
    loop = events.get_event_loop_policy().get_event_loop()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 93 passed, 1 warning in 11.95s ========================

Seems like the issue may have been resolved in one of the later commits.

**Pull request closed without merging**
